### PR TITLE
Added hello world script

### PR DESCRIPTION
**Pull request by mritul**

### CODE REVIEW

**Comment by fineanmol** [comment]
@mritul  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

**Comment by mritul** [comment]
Done starring the repo @fineanmol

**Comment by mritul** [comment]
@fineanmol  Can i get the hacktoberfest-added tag on the PR ?

**Comment by mritul** [comment]
@fineanmol can i get the "hacktober-accepted tag on my PR?"

**Pull request merged**
