### PR TITLE
Updated 2 files

### PR DESCRIPTION
**Pull request by khushimarothi**
I have updated contributors.md and script files.
please assign hacktoberfest labels.

### CODE REVIEW

**Comment by khushimarothi** [comment]
Starred this repo too

**Comment by fineanmol** [comment]
@khushimarothi  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

**Comment by khushimarothi** [comment]
> @khushimarothi Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

This project shows excluded on my hacktoberfest profile

**Comment by khushimarothi** [comment]
> > @khushimarothi Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.
> 
> Did that already. This project shows excluded on my hacktoberfest profile

@fineanmol

**Pull request merged**
