### PR TITLE
vishakha868_contributed

### PR DESCRIPTION
**Pull request by vishakha868**

### CODE REVIEW

**Comment by vishakha868** [comment]
hacktoberfest first pr

**Comment by fineanmol** [comment]
@vishakha868  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

**Comment by vishakha868** [comment]
> @vishakha868 Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

done

**Comment by vishakha868** [comment]
> @vishakha868 Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

can you add that label now

**Pull request merged**
