### PR TITLE
hello world of github

### PR DESCRIPTION
**Pull request by dixitt5**

### CODE REVIEW

**Comment by dixitt5** [comment]
@fineanmol can you plese add that label of hactober accepted. thanks :)

**Comment by dixitt5** [comment]
@fineanmol can you please add the hacktoberfest label , thanks :)

**Comment by fineanmol** [comment]
@dixitt5  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

**Comment by dixitt5** [comment]
Already did it! ;) @fineanmol

**Pull request merged**
