### PR TITLE
Added

### PR DESCRIPTION
**Pull request by Danuragtiwari**

### CODE REVIEW

**Comment by fineanmol** [comment]
@Danuragtiwari  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

**Comment by Danuragtiwari** [comment]
@fineanmol done sir

**Comment by Danuragtiwari** [comment]
@fineanmol sir why this repository is excluded from hacktoberfest 2022?

**Comment by fineanmol** [comment]
> @fineanmol sir why this repository is excluded from hacktoberfest 2022?

I have no idea, Someone must have reported it to the forum

**Comment by ItzLevvie** [comment]
This repository has been **_permanently_** excluded from Hacktoberfest 2022. This means that any pull requests (PRs) made to this repository **_will_** not be counted towards your contributions for Hacktoberfest 2022.

Please contribute to **_valuable_** repositories instead of sending pull requests (PRs) to repositories that are there to defeat the whole purpose of Hacktoberfest 2022.

Any repeated, continuous exclusions will automatically ban your account from participating in Hacktoberfest 2022.

**Pull request merged**
